# Generated by Django 4.2.5 on 2023-11-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=40)),
                ('telefone', models.CharField(max_length=15)),
                ('mensagem', models.TextField()),
            ],
        ),
    ]
